### ISSUE TITLE
language: add ability to unset variables

### ISSUE THREAD

**Issue by matthiaskrgr** [openvalidation/openvalidation#11]
In a hypothetical scenario we might declare a variable `car` inside file1.
Then we import file1 into file_main.
Inside main, we happen to use `car` without seeing that we set is to something special inside file_main which can lead to unexpected behaviour.

We might want to have have the ability to limit the scope of a variable to make sure we don't use one by accident.

**Comment by jages** [comment]
This is not currently planned.
