### ISSUE TITLE
can't validate URLs, rule can't contain "://"

### ISSUE THREAD

**Issue by matthiaskrgr** [openvalidation/openvalidation#18]
``
java -jar openvalidation-cli/target/openvalidation.jar --culture en --language javascript --rule "if the url is not https://www.example.com then 404 not found" --schema "{url: website }"
``
fails to parse
````

ERROR while compile language JavaScript:
java.nio.file.InvalidPathException: Illegal char <:> at index 23: if the url is not https://www.example.com then 404 not foundIllegal char <:> at index 23: if the url is not https://www.example.com then 404 not found
````
apparently we can't have `://` inside a rule which breaks cases like `https://`

**Comment by jages** [comment]
Binding this to #29 , we need a general way to escape chracters in input strings, to display them in return values.
