### ISSUE TITLE
possible code injection via json schema

### ISSUE THREAD

**Issue by matthiaskrgr** [openvalidation/openvalidation#19]
It is possible to craft a json schema with arbitrary keys that represent java keywords or java code.
This makes it very easy to force OV to generate invalid code and might make it possible generate arbitrary code from rules and a schema which is probably not intended.

rule:
``if the  break; break; is not a then ERROR``
schema:
``
{ ' break; break;': a  }
``

generated code:
```java
        huml.appendRule("",
                   ["break; break;"],
                   "ERROR",
                   function(model) { return huml.NOT_EQUALS(model.break; break;, "a");},
                   false
                );
```

**Comment by jages** [comment]
Also binding this to the same issue as #29
