### ISSUE TITLE
variable name is number if   "foo AS 1"

### ISSUE THREAD

**Issue by matthiaskrgr** [openvalidation/openvalidation#23]
The rule
````
1 AS 1
````
generates code with a variable name being a number:

````java
HUMLFramework.Variable 1 = huml.CreateVariable("1",
    (model) -> 1.0
);
````
which is not valid java code.

**Comment by matthiaskrgr** [comment]
Same goes for reserved language keywords:
```
1 AS true

2 AS for

3 AS continue

4 AS return
```

**Comment by jages** [comment]
possible duplicate of #29 , this should likely be blocked just for security reasons.
