### ISSUE TITLE
parsing of conditiongroups: operand after "and" is always a string

### ISSUE THREAD

**Issue by NLueg** [openvalidation/openvalidation#33]
## Expected Behavior

The parser should recognize the datatype of an operand after an `and`.
For example when I write `If  age`, `age` is recognizes as a decimal value by the parser.
This should also apply on the rule `If year smaller than another_int and age`.

## Current Behavior

No matter what datatype the operand after the logical connector has, it's always parsed as a string. This is also the case when I try to use a variable instead of a schema attribute.

After I add an operation which only works for decimal values (e.g. `smaller`), the parser understands, that it is a decimal value. I would expect, that the value of the operand is recognized even without an operation like at the start of a rule.

## Steps to Reproduce (for bugs)

I called the REST-API with this JSON:

```json
{
    "rule": "If age smaller than another_int and year ",
    "schema": "{age: 20, another_int: 10, year: 2000}",
    "culture": "en",
    "language": "Java"
}
```

I can reproduce this too with the german language:

```json
{
    "rule": "WENN Alter GERINGER Berufserfahrung UND Einkaufsliste.Preis ",
    "schema": "{Alter: 20, Einkaufsliste: { Preis: 20}}",
    "culture": "de",
    "language": "Java"
}
```
## Your Environment

* Version used: 0.0.1 (latest)
* Environment name and version (`mvn -v` and `java -version`):
* Operating System and version:
* Link to your project: https://github.com/NLueg/openvalidation

**Comment by jages** [comment]
can you elaborate further on this error? The snipped you provided is no valid rule.
The parsing steps might give you incomplete temporary results, because the rule is not complete.
Even when you input `If age smaller than another_int and year then error` to get rid of the initial error (message for no error message), there is no implicit operation specific to numeric values.

**Comment by NLueg** [comment]
I were just wondering, because the incomplete rule `If age` gives me the correct result.
After parsing this, the parser recognizes the correct datatype.

I would expect this behavior too in an connected operation.

**Comment by jages** [comment]
Data type resolution is a post process that is done before (or interpreted during) validation of the AST.
The resolution of condition and condition group might be different, when it comes to determination of types without operators.

Pinging @lionelpa

**Comment by NLueg** [comment]
@lionelpa Test-Ping
