### ISSUE TITLE
make sure OV does not touch files unneccessarily

### ISSUE THREAD

**Issue by matthiaskrgr** [openvalidation/openvalidation#40]
Make sure the cli does not touch files unneccessarily.

When OV-cli is integrated in a build pipeline of some program, we could have some input files containing natural language and use ov-cli to generated code sources as a build step.

Right now ov-cli just reads the files and generates new code sources every time it is executed regardless of whether the NL source has changed or not.
This will cause the source code files to be `touch`ed every time the program is built and may cause the build system to recompile the program altough no actual changes have been made which will slow down the developers workflow.

For example two `make` calls would finish in 1 second each but due to OV, they take 2 minutes since files have to be rebuilt and libraries have to be relinked etc.

I suggest to have a flag that makes the cli read the NL sources, translate them into the respective target language and then compare the newly translated code with the code that is already found in the repository.
We should only overwrite on-disk files with the in-memory translation if there is a difference to prevent uneccessarily slowing down the build.

**Comment by jages** [comment]
Caching of input files is currently not planned. In this stage of early development, we want to actively generate the entire AST or to pre-process the input every single time, therefore we do not plan to adress this in the foreseeable future.
