### ISSUE TITLE
Parsing of condition groups inside an constrained rule is different from a "normal" rule

### ISSUE THREAD

**Issue by NLueg** [openvalidation/openvalidation#41]
## Expected Behavior
Parsing of a condition group inside a constrained rule should behave the same as inside a normal rule.

## Current Behavior
It doesn't.

The following JSON of a constrained rule generates the following result.
```{json}
{
    "rule": "age must be greater than 18 and name must not equal test",
    "schema": "{ Alter: 20}",
    "empty" : true,
    "culture": "en",
    "language": "Java"
}
```

<img width="800" alt="shortrule_parsing" src="https://user-images.githubusercontent.com/48101693/65301921-b377a800-db79-11e9-8c64-8fdd94a8ae0d.PNG">

As you can see, the sources don't show everything I have written.
The parser recognizes both conditions, but doesn't shows them in the source-strings.

If I use a normal rule it behaves correct:

```{json}
{
    "rule": "If age is be greater than 18 and the name does not equal test",
    "schema": "{ Alter: 20}",
    "empty" : true,
    "culture": "en",
    "language": "Java"
}
```

<img width="900" alt="normalrule_parsing" src="https://user-images.githubusercontent.com/48101693/65301916-aa86d680-db79-11e9-878b-c1257bfca4f8.PNG">

**Comment by jages** [comment]
There is an issue with the tracking of the source here, this might be a result of having a special handler for condition groups within constraints (there is a very messy case if it contains an UNLESS-token, that required us to basically re-write a special case for almost any input in constraints).

I will look into it.

**Comment by NLueg** [comment]
Is there any update on this? @jages @lionelpa

**Comment by jages** [comment]
This is another example for why we need source maps. This feature is currently not actively being worked on, but we are aware of this issue.
