### ISSUE TITLE
Missing dependency for com.fasterxml.jackson.annotation when trying to execute IntegrationTestRunner

### ISSUE THREAD

**Issue by lionelpa** [openvalidation/openvalidation#43]
I followed the steps in the readme regarding the setup of the GeneratorCLI and the execution of the IntegrationTestRunner. Since it worked before I expected it to work but it doesnt.

## Error
It says it cannot find any of the com.fasterxml.jackson.annotation packages found in the generated "Address" classes generated by the GeneratorCLI. Fumbling around with marking directories as generated source etc. didnt help either.

## Steps to reproduction
1. fork/clone
2. build
3. follow the readme (Generate -> Run IntegrationTests)

**Comment by matthiaskrgr** [comment]
Shouldn't azure pipelines ci pick this up as well...?

**Comment by lionelpa** [comment]
I should have added that if i use "mvn clean test -Pintegration" everything works fine. Since the ci uses the same command (i guess, correct me if im wrong) this is not picked up.

It only occurs when trying to explicitly execute the IntegrationTestsRunner in IntelliJ

**Comment by jages** [comment]
This is an issue with your own work pipeline.
If you want to use the integration runner, i suggest making a private, custom maven profile to run it individually without any other tests.
