### ISSUE TITLE
Stackoverflow when having cyclic variable references

### ISSUE THREAD

**Issue by lionelpa** [openvalidation/openvalidation#55]
## Expected Behavior

A warning should occur informing the user of the reference cycle. 

## Current Behavior

Stackoverflow error when ASTVariable.getDataType() is called.
## Possible Solution

Extend validation of ASTVariables so that cyclic references can be detected.

## Steps to Reproduce (for bugs)

Simply run
```
x as y

y as z

z as x
```
in any end2ast test

**Comment by NLueg** [comment]
Duplicate of [Issue #13](https://github.com/openvalidation/openvalidation/issues/13)
