### ISSUE TITLE
Parsing of a condition group behaves different inside a rule and a variable

### ISSUE THREAD

**Issue by NLueg** [openvalidation/openvalidation#59]
I tried to parse the operation `age smaller 18 and age smaller 18` two times with Java as a programming language.
First I parsed it as a variable like `age smaller 18 and age smaller 18 as tmp_result` which leads to the parsed object you can see in `Expected Behavior`. So as you can guess, the result is totally fine.

Second I parsed it as a  rule like `If age smaller 18 and age smaller 18 then error` which leads to the parsed object you can see in `Current Behavior`.  As you can see, the source-string of the second operation is completely empty.

Note: This doesn't happen, when I change the condition a little that the strings of each don't exactly match.

## Expected Behavior

![image](https://user-images.githubusercontent.com/48101693/67755527-9c5d8d00-fa38-11e9-8af8-6900a5682f74.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/48101693/67755600-b9925b80-fa38-11e9-9e88-9e3d460676a8.png)

## Possible Solution

Don't use the same condition twice

## Context

I tried to test my modified REST-API

**Comment by jages** [comment]
I'm looking into it.
This is likely linked to how the sources are retroactively linked in AST creation and would require a large restructuring of the preprocessor to include proper sourcemaps.

**Comment by jages** [comment]
I'm closing this issue, there is currently no way to disect the source map without a major pre-processor rework to allow for source mapping. It's a feature we don't have any ETA on as of right now.
