### ISSUE TITLE
can't have comments between condition and return 

### ISSUE THREAD

**Issue by matthiaskrgr** [openvalidation/openvalidation#7]
````
if Satoshi is the name


COMMENT oh no


then hello world
````

fails to parse on the playground

**Comment by sbischoff-ai** [comment]
This is expected behaviour. Two consecutive line breaks divide global elements of the openVALIDATION ruleset. (As described [here](https://docs.openvalidation.io/grammatik/strukturierung-des-regelwerkes) in the docs.)
