### ISSUE TITLE
ONE_OF and NONE_OF are not working in combination with variables

### ISSUE THREAD

**Issue by Swaibu** [openvalidation/openvalidation#93]
## Expected Behavior
Usecase 1: 
```
Berlin, Paris , London as capital cities

the location must be one of the capital cities
```

Usecase 2: 
```
Berlin, Paris  or London as capital cities

the location must be one of the capital cities
```

schema
```
  location:""
```

## Current Behavior
Usecase 1:
comma separated list will actually not be resolved as an array

HUMLFramework.Variable capital_cities= huml.CreateVariable("capital_cities",
    (model) -> "Berlin, Paris or London"
);

Same behaviour by using numeric values

Usecase 2:
comma separated list will be parsed as a incomplete condition group

**Comment by lionelpa** [comment]
Specified two distinct usecases for this particular feature.

**Comment by lionelpa** [comment]
Issue closed since the pull request that addressed this issue has already been merged.
